itutakipci/account/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='account'

urlpatterns=[
    path('signup/', views.signup, name="register"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('login/', views.sign_in,name='login'),
    path('logout/',views.sign_out,name='logout'),
    path('confirmation_phase/',views.confirmation_phase,name="confirmation_phase")
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itutakipci/distribution/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name='distribution'

urlpatterns=[
    path('',views.Index.as_view(),name='home'),
    path('hocalar/<slug:slug>/',views.LecturerDistribution.as_view(),name='lecturer_distribution'),
    path('dersler/<slug:slug>/',views.LectureDistribution.as_view(),name='lecture_distribution'),
]



urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itutakipci/itutakipci/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('distribution.urls')),
    path('',include('account.urls')),
    url('^', include('django.contrib.auth.urls')),
]

itutakipci/distribution/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
# Create your models here.




class Lecture(models.Model):
    lecture=models.CharField(max_length=128,blank=False)
    slug = models.SlugField(max_length=20, unique=True)

    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.lecture)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.lecture

    class Meta:
        ordering = ['lecture']


class Lecturer(models.Model):
    lecturer=models.CharField(max_length=128,blank=False)
    lecture=models.ManyToManyField(Lecture)
    faculty=models.CharField(max_length=128)
    slug = models.SlugField(max_length=20, unique=True)

    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.lecturer)
        super().save(*args, **kwargs)

    def get_lectures(self):
        return ",".join([str(p) for p in self.lecture.all()])

    def __str__(self):
        return self.lecturer

    class Meta:
        ordering = ['lecturer']


class Semester(models.Model):
    semester=models.CharField(max_length=128,blank=False)

    def __str__(self):
        return self.semester

    class Meta:
        ordering = ['semester']


class Distribution(models.Model):
    # these are the images
    distribution=models.ImageField(upload_to='distribution/')
    created_on = models.DateTimeField(auto_now_add=True)
    semester=models.ForeignKey(Semester,on_delete=models.CASCADE,blank=False,default=0)
    lecturer=models.ForeignKey(Lecturer,on_delete=models.CASCADE,blank=False,default=0)
    lecture=models.ForeignKey(Lecture,on_delete=models.CASCADE,blank=False,default=0)


    def get_absolute_url(self):
        return reverse("home")

    class Meta:
        ordering = ['-created_on']


class Comment(models.Model):
    comment = models.TextField(max_length=256, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='comment_author',blank=True,null=True)
    author_security=models.ForeignKey(User, on_delete= models.CASCADE,related_name='comment_author_security')
    created_on = models.DateTimeField(auto_now_add=True)
    lecturer=models.ForeignKey(Lecturer,on_delete=models.CASCADE,blank=True,null=True)
    anon=models.BooleanField()


    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.comment

itutakipci/distribution/forms.py
from .models import Distribution
from django import forms
from .models import Distribution,Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['comment','anon']

itutakipci/distribution/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Distribution,Lecturer,Lecture,Comment
from .forms import CommentForm
from django.urls import reverse_lazy,reverse
from django.views.generic.edit import ModelFormMixin,FormMixin


# Create your views here.

class Index(generic.ListView):
    template_name='home.html'
    models=Lecturer
    queryset = Lecturer.objects.all()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ['lecturer_list'] = Lecturer.objects.order_by('lecturer')
        return context



class LecturerDistribution(FormMixin, generic.DetailView):
    model = Lecturer
    template_name = 'lecturer.html'
    context_object_name = 'post'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super(LecturerDistribution, self).get_context_data(**kwargs)
        context ['lecturer'] = self.object
        context ['distribution'] = Distribution.objects.filter(lecturer=self.object).order_by('lecture')
        context ['commentmodel_list'] = Comment.objects.filter(lecturer=self.object).order_by('-created_on')
        context['form'] = CommentForm(initial={'lecturer': self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.lecturer=self.object
        form.instance.author_security = self.request.user
        if form.instance.anon==True:
            pass
        else:
            form.instance.author=self.request.user
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('distribution:lecturer_distribution', kwargs={'slug': self.object.slug})


class LectureDistribution(generic.DetailView):
    model=Lecture
    template_name='lecture.html'

    def get_success_url(self):
        return reverse('lecture_distribution', kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ['distribution_'] = Distribution.objects.filter(lecture=self.object).order_by('-created_on')
        return context

itutakipci/distribution/templates/home.html
{% extends "base.html" %}
{%block content%}
{% load crispy_forms_tags %}

<div style="text-align:center;"class="container">
	<span class="baslik">İTÜ TAKİPÇİ</span>
</div>

<div class="container">
		<div class="form-group pull-right">
    <input type="text" class="search form-control" placeholder="Ara">
		</div>
		<span class="counter pull-right"></span>
		<table class="table table-hover results">
  	<thead>
    	<tr>
      	<th >Hoca</th>
				<th>Fakülte</th>
      	<th >Ders</th>
    	</tr>
    	<tr class="warning no-result">
      	<td><i class="fa fa-warning"></i> Sonuç Yok</td>
    	</tr>
  	</thead>
  	<tbody>
			{%for lec in lecturer_list%}
    	<tr>
      	<td>
					<p ><a style="text-decoration:none" href="{% url 'distribution:lecturer_distribution' slug=lec.slug%}">{{lec.lecturer}}</a></p>
      	</td>
				<td>
						<p>{{lec.faculty}}</p>
				</td>
      	<td>
					{%for ders in lec.lecture.all%}
						<a style="text-decoration:none" href="{% url 'distribution:lecture_distribution' slug=ders.slug%}">{{ders.lecture}}</a>,
					{% endfor%}
				</td>
    	</tr>
			{%endfor%}
  	</tbody>
</table>

</div>





<style >
		body{
  padding:20px 20px;
}

.results tr[visible='false'],
.no-result{
  display:none;
}

.results tr[visible='true']{
  display:table-row;
}

.counter{
  padding:8px;
  color:#ccc;
}


@import url('https://fonts.googleapis.com/css?family=Montserrat:900i&display=swap');


.baslik{

	font-family sans-serif;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size:70px;
	letter-spacing:0.1em;
  -webkit-text-fill-color: transparent;
  -webkit-text-stroke-width: 3px;
  -webkit-text-stroke-color: #002855;
}
	</style>

<script>
	$(document).ready(function() {
  $(".search").keyup(function () {
    var searchTerm = $(".search").val();
    var listItem = $('.results tbody').children('tr');
    var searchSplit = searchTerm.replace(/ /g, "'):containsi('")

  $.extend($.expr[':'], {'containsi': function(elem, i, match, array){
        return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
    }
  });

  $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function(e){
    $(this).attr('visible','false');
  });

  $(".results tbody tr:containsi('" + searchSplit + "')").each(function(e){
    $(this).attr('visible','true');
  });

  var jobCount = $('.results tbody tr[visible="true"]').length;

  if(jobCount == '0') {$('.no-result').show();}
    else {$('.no-result').hide();}
		  });
});
</script>



{% endblock content%}

itutakipci/distribution/templates/lecture.html
{% extends "base.html" %}
{%block content%}




<div class="container">

	<h1 style="text-align:center;">Tüm Hocalara ait {{lecture.lecture}} Dağılımları</h1>
	<hr>
	{% for i in distribution_%}
	<div class='img1'>
		<img src="{{ i.distribution.url }}">
		<p style="text-align:center;">{{i.lecturer}} | {{i.semester}}</p>

	</div>
  {% endfor %}

</div>

<style >
	img {
	    width:  300px;
	    height: 300px;
	    object-fit: cover;
	}
	.img1{
		float: left;
		margin:20px;

</style>






{% endblock content%}

itutakipci/distribution/templates/lecturer.html
{% extends "base.html" %}
{%block content%}
{% load crispy_forms_tags %}



<div class="container">
	<h1 style="text-align:center;">{{lecturer.lecturer}}</h1>
	<hr>
	{% for i in distribution%}
	<div class='img1'>
		<img name="pic" src="{{ i.distribution.url }}">
		<p style="text-align:center;">{{i.lecture}} | {{i.semester}}</p>
	</div>
  {% endfor %}
</div>

<div class="container">
	<table class="table">
	</table>
</div>


<div class="container">
		{% if user.is_authenticated%}
	 <button style="float:right;"type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Yorum Ekle</button>
	 <h1 style="text-align:center;">Hoca hakkında Yorumlar</h1>
	 {% else %}
	 <h1 style="text-align:center;">Hoca hakkında Yorumlar</h1>
	 <p style="text-align:right;">Yorum yapmak için <a style="text-decoration:none;" href="{% url 'account:login' %}">Giriş</a> yap!</p>
	 {% endif%}
	{% for j in commentmodel_list%}
	<hr>
	<h4>{{j.comment}}</h4>
		{% if j.author is None%}
		<p>Anon</p>
		{% else %}
		<p>{{j.author}}</p>
		{% endif %}
	{% endfor %}
</div>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
 <div class="modal-dialog" role="document">
	 <div class="modal-content">
		 <div class="modal-header">
			 <h5 class="modal-title" id="exampleModalLabel">Yorum</h5>
		 </div>
		 <div class="modal-body">
			 <form method="post" style="margin-top: 1.3em;">
				 {% csrf_token %}
				 ​<textarea name="comment" rows="10" cols="50"></textarea>
				 <br>
				 <input type="checkbox" name="anon" text="Anonim" >
				 <label for="anon">Anonim Yorumlamak için Tıkla!</label>
				 <div class="modal-footer">
					 <button type="submit" class="btn btn-primary">Yorumla</button>
					 <button type="submit" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
				 </div>
			 </form>
		 </div>
	 </div>
 </div>
</div>
<style >
	img {
	    width:  300px;
	    height: 300px;
	    object-fit: cover;
	}
	.img1{
		float: left;
		margin:20px;

	}
	.comments{
		text-align:center
	}
</style>
{% endblock content%}